### ISSUE TITLE
setOverwrite method

### ISSUE THREAD

**Issue by jonaswebdev** [xsuchy09/utm-cookie#1]
Just an observation, for the method UtmCookie::setOverwrite() work properly with **false** value, it must be defined before UtmCookie::init();.

Examples:
OK -works well
```
UtmCookie::setOverwrite(false);
UtmCookie::init();

```
FAIL - not work well
```
UtmCookie::init();
UtmCookie::setOverwrite(false);
```

BTW, Thanks a lot for this code/script, saved some days of work :)

**Comment by xsuchy09** [comment]
Hello. Thanks for your comment/issue. In example is called `setName` method after `setOverwrite`. This method will empty `self::$utmCookie`, so there is no issue. But without `setName` method issue is confirmed. So I change it and now `self::$utmCookie` is emptied in `setOverwrite` method too. Thanks again and have a nice day.
