### ISSUE TITLE
Incorrect return type on get() ?

### ISSUE THREAD

**Issue by alexciarlillo** [xsuchy09/utm-cookie#3]
It looks like in 2.0 the return value type for the `get()` method is incorrect. It specifies null or string, but it should allow array. `getObject()` calls `get()` with a null parameter which should return an array of all cookies, which is then cast to an object.

**Comment by xsuchy09** [comment]
Confirmed and fixed. See [2.0.1](https://github.com/xsuchy09/utm-cookie/tree/2.0.1).
