### ISSUE TITLE
Please add tag 2.0.3

### ISSUE THREAD

**Issue by rshkabko** [xsuchy09/utm-cookie#5]
Composer doesn't see new version - https://packagist.org/packages/xsuchy09/utm-cookie

**Comment by xsuchy09** [comment]
Tag was added but I didn't check composer.json where was the version set as 2.0.2 (so packagist see that as version mismatched and ignore 2.0.3 release). Version was removed from composer.json and tag 2.0.4 was added. Thanks for the info.

**Comment by rshkabko** [comment]
Thank you for a quick fix!
